import { describe, it, expect } from "bun:test";
import {
  computeBoundParamsHash,
  computeStealthDataHash,
  createTransferBoundParams,
  createUnshieldBoundParams,
  createRedeemBoundParams,
} from "../../src/bound-params";
import { bigintTo32Bytes } from "../../src/instructions";

/**
 * Cross-language parity tests — these test vectors must produce identical
 * results in both TypeScript (SDK) and Rust (on-chain program).
 *
 * Rust vectors generated by: cargo test -- test_bound_params_cross_lang_vectors --nocapture
 *
 * NOTE: unshield vectors changed in the multi-output migration because
 * unshieldAddress is now SHA256(concat(owners)) instead of raw owner bytes.
 * Transfer and redeem (single script) vectors are unchanged.
 */
describe("boundParamsHash cross-language parity", () => {
  const CHAIN_ID = 103n;
  const ZERO_STEALTH = new Uint8Array(32);

  it("transfer: chain_id=103, zero stealth", () => {
    const params = createTransferBoundParams(ZERO_STEALTH, CHAIN_ID);
    const hash = computeBoundParamsHash(params);
    const hashBytes = bigintTo32Bytes(hash);
    const hashHex = Array.from(hashBytes).map(b => b.toString(16).padStart(2, "0")).join("");

    // Must match Rust VECTOR_transfer (unchanged)
    expect(hashHex).toBe("06db1d31bd2ae34ed282aa200e61b183b67320420360c035d947c5263a21794d");
  });

  it("unshield: chain_id=103, address=0xAA*32, zero stealth (multi-output format)", () => {
    const addr = new Uint8Array(32).fill(0xAA);
    // Now uses SHA256(addr) as destinations_hash (was raw addr before)
    const params = createUnshieldBoundParams(addr, ZERO_STEALTH, CHAIN_ID);
    const hash = computeBoundParamsHash(params);
    const hashBytes = bigintTo32Bytes(hash);
    const hashHex = Array.from(hashBytes).map(b => b.toString(16).padStart(2, "0")).join("");

    // Must match Rust VECTOR_unshield (regenerated for multi-output: SHA256(owner) format)
    expect(hashHex).toBe("0d9a935c0e397e121313f4aaebdda5f5da92ba4dd6daae85e6934a150d97dd0f");
  });

  it("redeem: chain_id=103, btcScript=5120+0xBB*32, zero stealth", () => {
    const script = new Uint8Array(34);
    script[0] = 0x51;
    script[1] = 0x20;
    script.fill(0xBB, 2);
    const params = createRedeemBoundParams(script, ZERO_STEALTH, CHAIN_ID);
    const hash = computeBoundParamsHash(params);
    const hashBytes = bigintTo32Bytes(hash);
    const hashHex = Array.from(hashBytes).map(b => b.toString(16).padStart(2, "0")).join("");

    // Must match Rust VECTOR_redeem (unchanged — single script SHA256 same as before)
    expect(hashHex).toBe("09c09ef658e863fbf480678e3459ddbd7b3684484742a832213c306a5816a845");
  });

  it("transfer with non-zero stealth: chain_id=103, stealth=0xCC*32", () => {
    const stealthNz = new Uint8Array(32).fill(0xCC);
    const params = createTransferBoundParams(stealthNz, CHAIN_ID);
    const hash = computeBoundParamsHash(params);
    const hashBytes = bigintTo32Bytes(hash);
    const hashHex = Array.from(hashBytes).map(b => b.toString(16).padStart(2, "0")).join("");

    // Must match Rust VECTOR_transfer_nz (unchanged)
    expect(hashHex).toBe("22de1a31d6fa3eafa4d52d4898c6318aef2fe57e55c117c2ecf9dcffba6cb963");
  });

  it("multi-output unshield: two recipients produce different hash than single", () => {
    const addr1 = new Uint8Array(32).fill(0xAA);
    const addr2 = new Uint8Array(32).fill(0xBB);
    const singleHash = computeBoundParamsHash(
      createUnshieldBoundParams(addr1, ZERO_STEALTH, CHAIN_ID)
    );
    const multiHash = computeBoundParamsHash(
      createUnshieldBoundParams([addr1, addr2], ZERO_STEALTH, CHAIN_ID)
    );
    expect(singleHash).not.toBe(multiHash);
  });

  it("multi-output redeem: two scripts produce different hash than single", () => {
    const script1 = new Uint8Array([0x51, 0x20, 0xAA, 0xBB]);
    const script2 = new Uint8Array([0x51, 0x20, 0xCC, 0xDD]);
    const singleHash = computeBoundParamsHash(
      createRedeemBoundParams(script1, ZERO_STEALTH, CHAIN_ID)
    );
    const multiHash = computeBoundParamsHash(
      createRedeemBoundParams([script1, script2], ZERO_STEALTH, CHAIN_ID)
    );
    expect(singleHash).not.toBe(multiHash);
  });
});

describe("computeStealthDataHash", () => {
  it("returns SHA256 of empty for empty array", () => {
    const hash = computeStealthDataHash([]);
    // SHA256("") = e3b0c442...
    expect(hash[0]).toBe(0xe3);
    expect(hash.length).toBe(32);
    // NOT all zeros — must match on-chain sha256(empty_slice)
    expect(hash).not.toEqual(new Uint8Array(32));
  });

  it("produces deterministic output", () => {
    const sd1 = new Uint8Array(72).fill(0xAA);
    const sd2 = new Uint8Array(72).fill(0xBB);
    const hash1 = computeStealthDataHash([sd1, sd2]);
    const hash2 = computeStealthDataHash([sd1, sd2]);
    expect(hash1).toEqual(hash2);
  });

  it("different data produces different hashes", () => {
    const sd1 = new Uint8Array(72).fill(0xAA);
    const sd2 = new Uint8Array(72).fill(0xBB);
    const hashA = computeStealthDataHash([sd1]);
    const hashB = computeStealthDataHash([sd2]);
    expect(hashA).not.toEqual(hashB);
  });
});

describe("boundParamsHash properties", () => {
  const STEALTH = new Uint8Array(32);

  it("different modes produce different hashes", () => {
    const transfer = computeBoundParamsHash(createTransferBoundParams(STEALTH));
    const unshield = computeBoundParamsHash(
      createUnshieldBoundParams(new Uint8Array(32), STEALTH)
    );
    const redeem = computeBoundParamsHash(
      createRedeemBoundParams(new Uint8Array([0x51, 0x20]), STEALTH)
    );
    expect(transfer).not.toBe(unshield);
    expect(transfer).not.toBe(redeem);
    expect(unshield).not.toBe(redeem);
  });

  it("different stealth data produces different hashes", () => {
    const stealthA = new Uint8Array(32).fill(0x11);
    const stealthB = new Uint8Array(32).fill(0x22);
    const hashA = computeBoundParamsHash(createTransferBoundParams(stealthA));
    const hashB = computeBoundParamsHash(createTransferBoundParams(stealthB));
    expect(hashA).not.toBe(hashB);
  });

  it("different btcScript produces different redeem hashes", () => {
    const stealth = new Uint8Array(32);
    const scriptA = new Uint8Array([0x51, 0x20, 0xAA]);
    const scriptB = new Uint8Array([0x51, 0x20, 0xBB]);
    const hashA = computeBoundParamsHash(createRedeemBoundParams(scriptA, stealth));
    const hashB = computeBoundParamsHash(createRedeemBoundParams(scriptB, stealth));
    expect(hashA).not.toBe(hashB);
  });
});
