"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { InfoTip } from "@/components/ui/info-tip";
import {
  createDelegatedViewKey,
  deriveKeysFromSeed,
  fingerprintDelegatedKey,
  makeDelegationRecord,
  serializeDelegatedViewKey,
  ViewPermissions,
  type DelegationRecord,
} from "@utxopia/sdk";

const STORAGE_KEY = "utxopia.delegations.v1";

interface UIRecord extends DelegationRecord {
  // Local-only — never written into the encrypted key file.
  revoked?: boolean;
}

function loadFromStorage(): UIRecord[] {
  if (typeof window === "undefined") return [];
  try {
    return JSON.parse(window.localStorage.getItem(STORAGE_KEY) ?? "[]");
  } catch {
    return [];
  }
}

function saveToStorage(rows: UIRecord[]) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(rows));
}

export default function IssuedDelegationsPage() {
  const [records, setRecords] = useState<UIRecord[]>([]);
  const [issueOpen, setIssueOpen] = useState(false);
  const importRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    setRecords(loadFromStorage());
  }, []);

  const importJson = useCallback(async (file: File) => {
    const text = await file.text();
    try {
      const rows = JSON.parse(text) as DelegationRecord[];
      const next = [...records];
      for (const r of rows) {
        if (!next.find((x) => x.delegationId === r.delegationId)) {
          next.push(r);
        }
      }
      setRecords(next);
      saveToStorage(next);
    } catch {
      alert("Invalid delegations.json — expected an array of DelegationRecord objects");
    }
  }, [records]);

  const revoke = useCallback((delegationId: string) => {
    const next = records.map((r) =>
      r.delegationId === delegationId ? { ...r, revoked: true } : r,
    );
    setRecords(next);
    saveToStorage(next);
  }, [records]);

  return (
    <div className="min-h-screen bg-gradient-to-b from-black to-zinc-950 text-white">
      <SiteHeader />
      <main className="mx-auto max-w-5xl px-4 py-12">
        <div className="flex items-baseline justify-between gap-4">
          <div className="flex items-center gap-2">
            <h1 className="text-3xl font-semibold tracking-tight">Issued delegations</h1>
            <InfoTip label="About Issued delegations">
              Your record of every delegated viewing key you've handed out — the
              secret key material itself is never stored here, only public
              metadata. Revoke is local-only (it just marks the record; the
              recipient's copy of the key still works until the wall-clock
              expiry).
            </InfoTip>
          </div>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={() => importRef.current?.click()}
              className="rounded-md border border-zinc-700 px-3 py-1.5 text-xs text-zinc-200 hover:border-zinc-500"
            >
              Import delegations.json
            </button>
            <button
              type="button"
              onClick={() => setIssueOpen(true)}
              className="rounded-md bg-emerald-500 px-3 py-1.5 text-xs font-medium text-black hover:bg-emerald-400"
            >
              New delegation
            </button>
            <input
              ref={importRef}
              type="file"
              accept="application/json,.json"
              className="hidden"
              onChange={async (e) => {
                const f = e.target.files?.[0];
                if (f) await importJson(f);
              }}
            />
          </div>
        </div>
        {records.length === 0 ? (
          <div className="mt-10 rounded-xl border border-zinc-800 bg-zinc-900/40 p-8 text-center text-sm text-zinc-400">
            No delegations recorded yet. Issue one with{" "}
            <span className="font-mono text-xs">New delegation</span> above,
            or import a <span className="font-mono text-xs">~/.utxopia/delegations.json</span>{" "}
            generated by the CLI.
          </div>
        ) : (
          <section className="mt-6 overflow-x-auto rounded-xl border border-zinc-800 bg-zinc-900/40">
            <table className="min-w-full text-left text-xs">
              <thead className="text-zinc-500">
                <tr>
                  <th className="px-3 py-2">Fingerprint</th>
                  <th className="px-3 py-2">Label</th>
                  <th className="px-3 py-2">Recipient</th>
                  <th className="px-3 py-2">Slot range</th>
                  <th className="px-3 py-2">Expires</th>
                  <th className="px-3 py-2">Issued</th>
                  <th className="px-3 py-2"></th>
                </tr>
              </thead>
              <tbody className="font-mono text-[11px] text-zinc-300">
                {records.map((r) => (
                  <tr
                    key={r.delegationId}
                    className={`border-t border-zinc-800/60 ${r.revoked ? "opacity-40 line-through" : ""}`}
                  >
                    <td className="px-3 py-2">{r.fingerprint.slice(0, 16)}…</td>
                    <td className="px-3 py-2">{r.label ?? "—"}</td>
                    <td className="px-3 py-2">{r.recipient ?? "—"}</td>
                    <td className="px-3 py-2">
                      [{r.fromSlot ?? "∗"}, {r.toSlot ?? "∗"}]
                    </td>
                    <td className="px-3 py-2">
                      {r.expiresAt ? new Date(r.expiresAt).toISOString().slice(0, 10) : "never"}
                    </td>
                    <td className="px-3 py-2">
                      {new Date(r.issuedAt).toISOString().slice(0, 10)}
                    </td>
                    <td className="px-3 py-2 text-right">
                      {!r.revoked && (
                        <button
                          type="button"
                          onClick={() => revoke(r.delegationId)}
                          className="text-zinc-500 hover:text-red-400"
                        >
                          revoke
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {issueOpen && (
          <IssueModal
            onClose={() => setIssueOpen(false)}
            onIssued={(rec) => {
              const next = [...records, rec];
              setRecords(next);
              saveToStorage(next);
            }}
          />
        )}
      </main>
      <SiteFooter />
    </div>
  );
}

function IssueModal({
  onClose,
  onIssued,
}: {
  onClose: () => void;
  onIssued: (rec: UIRecord) => void;
}) {
  const [seedHex, setSeedHex] = useState("");
  const [password, setPassword] = useState("");
  const [label, setLabel] = useState("");
  const [recipient, setRecipient] = useState("");
  const [fromSlot, setFromSlot] = useState("");
  const [toSlot, setToSlot] = useState("");
  const [expiresInHours, setExpiresInHours] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [working, setWorking] = useState(false);

  const handleIssue = useCallback(async () => {
    setError(null);
    setWorking(true);
    try {
      if (seedHex.length !== 64) {
        throw new Error("seed must be exactly 64 hex chars");
      }
      if (!password) throw new Error("password required");

      const seed = new Uint8Array(32);
      for (let i = 0; i < 32; i++) {
        seed[i] = parseInt(seedHex.substring(2 * i, 2 * i + 2), 16);
      }
      const keys = deriveKeysFromSeed(seed);
      const expiresAt = expiresInHours
        ? Date.now() + Number(expiresInHours) * 3_600_000
        : undefined;
      const delegated = createDelegatedViewKey(keys, ViewPermissions.FULL, {
        label: label || undefined,
        fromSlot: fromSlot ? Number(fromSlot) : undefined,
        toSlot: toSlot ? Number(toSlot) : undefined,
        expiresAt,
      });

      const blob = await serializeDelegatedViewKey(delegated, password);
      const record: UIRecord = makeDelegationRecord(delegated, {
        recipient: recipient || undefined,
      });

      // Trigger download of the encrypted key file
      const a = document.createElement("a");
      const url = URL.createObjectURL(
        new Blob([blob], { type: "application/json" }),
      );
      a.href = url;
      a.download = `utxopia-delegation-${fingerprintDelegatedKey(delegated).slice(0, 8)}.json`;
      a.click();
      URL.revokeObjectURL(url);

      onIssued(record);
      onClose();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setWorking(false);
    }
  }, [seedHex, password, label, recipient, fromSlot, toSlot, expiresInHours, onClose, onIssued]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 px-4">
      <div className="w-full max-w-md rounded-xl border border-zinc-800 bg-zinc-950 p-6 shadow-xl">
        <h2 className="text-lg font-semibold">Issue delegated viewing key</h2>
        <p className="mt-1 text-xs text-zinc-400">
          Encrypted with your password; the encrypted JSON downloads to your
          device. Only the public metadata is added to this audit trail.
        </p>
        <div className="mt-5 grid gap-3">
          <Field label="Seed (32 bytes, 64 hex chars)">
            <input
              type="password"
              value={seedHex}
              onChange={(e) => setSeedHex(e.target.value.toLowerCase().replace(/[^0-9a-f]/g, ""))}
              className="w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 font-mono text-xs text-zinc-100 outline-none focus:border-zinc-500"
            />
          </Field>
          <Field label="Password (encrypts the exported key)">
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-zinc-100 outline-none focus:border-zinc-500"
            />
          </Field>
          <div className="grid grid-cols-2 gap-3">
            <Field label="Label (optional)">
              <input
                value={label}
                onChange={(e) => setLabel(e.target.value)}
                className="w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-zinc-100 outline-none focus:border-zinc-500"
              />
            </Field>
            <Field label="Recipient (optional)">
              <input
                value={recipient}
                onChange={(e) => setRecipient(e.target.value)}
                className="w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-zinc-100 outline-none focus:border-zinc-500"
              />
            </Field>
          </div>
          <div className="grid grid-cols-3 gap-3">
            <Field label="From slot">
              <input
                inputMode="numeric"
                value={fromSlot}
                onChange={(e) => setFromSlot(e.target.value.replace(/[^\d]/g, ""))}
                className="w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-zinc-100 outline-none focus:border-zinc-500"
              />
            </Field>
            <Field label="To slot">
              <input
                inputMode="numeric"
                value={toSlot}
                onChange={(e) => setToSlot(e.target.value.replace(/[^\d]/g, ""))}
                className="w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-zinc-100 outline-none focus:border-zinc-500"
              />
            </Field>
            <Field label="Expires in (hours)">
              <input
                inputMode="numeric"
                value={expiresInHours}
                onChange={(e) => setExpiresInHours(e.target.value.replace(/[^\d]/g, ""))}
                className="w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-zinc-100 outline-none focus:border-zinc-500"
              />
            </Field>
          </div>
        </div>
        {error && (
          <div className="mt-3 rounded border border-red-900 bg-red-950/40 p-2 text-xs text-red-300">
            {error}
          </div>
        )}
        <div className="mt-5 flex justify-end gap-2">
          <button
            type="button"
            onClick={onClose}
            className="rounded-md border border-zinc-700 px-3 py-1.5 text-xs text-zinc-200 hover:border-zinc-500"
          >
            Cancel
          </button>
          <button
            type="button"
            disabled={working}
            onClick={handleIssue}
            className="rounded-md bg-emerald-500 px-3 py-1.5 text-xs font-medium text-black hover:bg-emerald-400 disabled:opacity-40"
          >
            {working ? "Issuing…" : "Issue + download"}
          </button>
        </div>
      </div>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="flex flex-col gap-1 text-xs text-zinc-400">
      {label}
      {children}
    </label>
  );
}
