#!/usr/bin/env bash
#
# sync-env.sh — Single source of truth config generator
#
# Reads {network}-state.json and generates ALL config files:
#   1. backend/.env.{network}          + symlink backend/.env
#   2. aegis-app/.env.{network}        + symlink aegis-app/.env.local
#   3. aegis-app/src/lib/networks.json (frontend config)
#
# Usage:
#   ./scripts/sync-env.sh                           # defaults to localnet
#   AEGIS_NETWORK=devnet ./scripts/sync-env.sh      # switch to devnet
#
# After deploying: update scripts/devnet-state.json, then run this script.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
NETWORK="${AEGIS_NETWORK:-localnet}"

echo "=== Aegis Config Sync ==="
echo "Network: $NETWORK"
echo ""

# ─── Load state file ──────────────────────────────────────────────────────────

case "$NETWORK" in
  localnet)
    STATE_FILE="$ROOT/scripts/e2e/localnet-state.json"
    ;;
  devnet)
    STATE_FILE="$ROOT/scripts/devnet-state.json"
    ;;
  *)
    echo "ERROR: Unknown network '$NETWORK'. Use: localnet, devnet"
    exit 1
    ;;
esac

if [ ! -f "$STATE_FILE" ]; then
  echo "ERROR: $STATE_FILE not found."
  echo "Run the deploy/init script first."
  exit 1
fi

# Helper to read JSON fields (works without jq)
jval() {
  python3 -c "import json,sys; d=json.load(open('$STATE_FILE')); print(d.get('$1',''))"
}

# ─── Read all values from state file ──────────────────────────────────────────

PROGRAM_ID=$(jval aegisProgramId)
BTC_LC_ID=$(jval btcLightClientId)
ZKBTC_MINT=$(jval zkbtcMint)
POOL_STATE=$(jval poolState)
COMMITMENT_TREE=$(jval commitmentTree)
POOL_VAULT=$(jval poolVault)
FROST_VAULT=$(jval frostVault)
POOL_AUTHORITY=$(jval poolAuthority)

WSOL_MINT=$(jval wsolMint)
USDC_MINT=$(jval tUsdcMint)
USDT_MINT=$(jval tUsdtMint)
JUPUSD_MINT=$(jval jupUsdMint)
WSOL_VAULT=$(jval wsolVault)
USDC_VAULT=$(jval tUsdcVault)
USDT_VAULT=$(jval tUsdtVault)
JUPUSD_VAULT=$(jval jupUsdVault)

GROUP_PUBKEY=$(jval btcXOnlyPubKey)
POOL_BTC_ADDR=$(jval poolBtcAddress)
BTC_NETWORK=$(jval btcNetwork)
SOLANA_RPC=$(jval solanaRpc)
BACKEND_URL=$(jval backendUrl)

# Defaults for fields not in state file
BTC_NETWORK="${BTC_NETWORK:-testnet4}"
SOLANA_RPC="${SOLANA_RPC:-https://api.devnet.solana.com}"
BACKEND_URL="${BACKEND_URL:-http://localhost:3001}"

# Network-specific overrides
case "$NETWORK" in
  localnet)
    SOLANA_RPC="${SOLANA_RPC:-http://localhost:8899}"
    BTC_NETWORK="${BTC_NETWORK:-regtest}"
    BACKEND_URL="${BACKEND_URL:-http://localhost:3001}"
    BTC_EXPLORER="http://localhost:3002/regtest"
    ESPLORA_URL="http://localhost:3002/regtest/api"
    MEMPOOL_WS="false"
    ;;
  devnet)
    BTC_EXPLORER="https://mempool.space/testnet4"
    ESPLORA_URL="https://mempool.space/testnet4/api"
    MEMPOOL_WS="true"
    ;;
esac

echo "Program ID:    $PROGRAM_ID"
echo "zkBTC Mint:    $ZKBTC_MINT"
echo "BTC LC:        $BTC_LC_ID"
echo "Group Pubkey:  ${GROUP_PUBKEY:0:16}..."
echo ""

# ─── 1. Generate backend/.env.{network} ──────────────────────────────────────

BACKEND_ENV="$ROOT/backend/.env.$NETWORK"
cat > "$BACKEND_ENV" << EOF
# Aegis Backend — $NETWORK (auto-generated by sync-env.sh)
# Source: $STATE_FILE
# Re-generate: AEGIS_NETWORK=$NETWORK ./scripts/sync-env.sh

# ─── Solana ──────────────────────────────────────────────────────────────────
AEGIS_PROGRAM_ID=$PROGRAM_ID
AEGIS_ZKBTC_MINT=$ZKBTC_MINT
AEGIS_NETWORK=$NETWORK
AEGIS_SOLANA_RPC=$SOLANA_RPC
SOLANA_RPC_URL=$SOLANA_RPC
BTC_LIGHT_CLIENT_PROGRAM_ID=$BTC_LC_ID

# ─── Bitcoin ─────────────────────────────────────────────────────────────────
AEGIS_BITCOIN_NETWORK=$BTC_NETWORK
AEGIS_BITCOIN_RPC=$ESPLORA_URL
ESPLORA_URL=$ESPLORA_URL
MEMPOOL_API_URL=$ESPLORA_URL
POOL_RECEIVE_ADDRESS=$POOL_BTC_ADDR

# ─── FROST Signing ───────────────────────────────────────────────────────────
AEGIS_SIGNING_MODE=frost
AEGIS_FROST_THRESHOLD=2
AEGIS_FROST_PARTICIPANTS=3
AEGIS_FROST_SIGNER_URLS=http://localhost:9001,http://localhost:9002,http://localhost:9003
AEGIS_FROST_KEY_SHARE=placeholder
AEGIS_FROST_GROUP_PUBKEY=$GROUP_PUBKEY
AEGIS_FROST_API_KEY=29372dc836a25d7bdcdbd2fa63fbfcc0d00f06ca710a3aa935b61cf5d6426912

# ─── Tracker & Indexer ───────────────────────────────────────────────────────
TRACKER_API_PORT=3001
DEPOSIT_DB_PATH=data/deposits.db
INDEXER_DB_PATH=data/events.db
INDEXER_POLL_INTERVAL_SECS=10
AEGIS_DEMO_MODE=1

# ─── Keypairs ────────────────────────────────────────────────────────────────
VERIFIER_KEYPAIR=verifier-keypair.json
RELAYER_KEYPAIR=[50,128,114,217,238,93,48,208,84,69,168,140,72,35,173,128,57,239,14,139,145,69,241,221,89,52,36,156,104,238,166,101,13,98,59,211,107,90,137,69,248,31,168,162,72,104,198,209,65,164,43,83,227,202,213,91,45,163,238,203,91,107,68,170]

# ─── WebSocket & Header Relay ────────────────────────────────────────────────
MEMPOOL_WS_ENABLED=$MEMPOOL_WS
MEMPOOL_WS_URL=wss://mempool.space/testnet4/api/v1/ws
HEADER_RELAY_ENABLED=$MEMPOOL_WS
HEADER_BATCH_SIZE=5

# ─── Fees ────────────────────────────────────────────────────────────────────
RELAYER_FEE_SATS=500
AEGIS_BROADCAST_MODE=real

# ─── API Auth ────────────────────────────────────────────────────────────────
BACKEND_API_KEY=aegis-backend-2026

# ─── Allowed Origins ─────────────────────────────────────────────────────────
ALLOWED_ORIGIN=http://localhost:3000

# ─── Logging ─────────────────────────────────────────────────────────────────
RUST_LOG=info,zkbtc=debug
EOF

echo "✓ Generated $BACKEND_ENV"
ln -sf ".env.$NETWORK" "$ROOT/backend/.env"
echo "✓ Symlinked backend/.env → .env.$NETWORK"

# ─── 2. Generate aegis-app/.env.{network} ────────────────────────────────────

FRONTEND_ENV="$ROOT/aegis-app/.env.$NETWORK"
cat > "$FRONTEND_ENV" << EOF
# Aegis Frontend — $NETWORK (auto-generated by sync-env.sh)
# Source: $STATE_FILE
# Re-generate: AEGIS_NETWORK=$NETWORK ./scripts/sync-env.sh

NEXT_PUBLIC_NETWORK=$NETWORK
NEXT_PUBLIC_SOLANA_RPC_URL=$SOLANA_RPC
NEXT_PUBLIC_BTC_NETWORK=$BTC_NETWORK
NEXT_PUBLIC_AEGIS_PROGRAM_ID=$PROGRAM_ID
NEXT_PUBLIC_ZKBTC_MINT=$ZKBTC_MINT
EOF

[ -n "$USDC_MINT" ] && echo "NEXT_PUBLIC_USDC_MINT=$USDC_MINT" >> "$FRONTEND_ENV"
[ -n "$USDT_MINT" ] && echo "NEXT_PUBLIC_USDT_MINT=$USDT_MINT" >> "$FRONTEND_ENV"
[ -n "$WSOL_MINT" ] && echo "NEXT_PUBLIC_WSOL_MINT=$WSOL_MINT" >> "$FRONTEND_ENV"
[ -n "$JUPUSD_MINT" ] && echo "NEXT_PUBLIC_JUPUSD_MINT=$JUPUSD_MINT" >> "$FRONTEND_ENV"

cat >> "$FRONTEND_ENV" << EOF

# Backend API
BACKEND_API_URL=$BACKEND_URL
NEXT_PUBLIC_BACKEND_API_URL=$BACKEND_URL
BACKEND_API_KEY=localnet-dev-key
EOF

echo "✓ Generated $FRONTEND_ENV"
ln -sf ".env.$NETWORK" "$ROOT/aegis-app/.env.local"
echo "✓ Symlinked aegis-app/.env.local → .env.$NETWORK"

# ─── 3. Generate aegis-app/src/lib/networks.json ─────────────────────────────
#
# This is the frontend's runtime config. We update ONLY the current network's
# section, preserving other networks' config.

NETWORKS_JSON="$ROOT/aegis-app/src/lib/networks.json"

# Build the network block with python3 (no jq needed)
python3 << PYEOF
import json, os

networks_path = "$NETWORKS_JSON"

# Load existing networks.json
if os.path.exists(networks_path):
    with open(networks_path) as f:
        networks = json.load(f)
else:
    networks = {}

# Update the current network section
networks["$NETWORK"] = {
    "solana": {
        "rpcUrl": "$SOLANA_RPC",
        "aegisProgramId": "$PROGRAM_ID",
        "btcLightClientId": "$BTC_LC_ID",
        "chadbufferId": "C5RpjtTMFXKVZCtXSzKXD4CDNTaWBg3dVeMfYvjZYHDF"
    },
    "tokens": {
        "zkbtcMint": "$ZKBTC_MINT",
        "usdcMint": "$USDC_MINT",
        "usdtMint": "$USDT_MINT",
        "wsolMint": "$WSOL_MINT",
        "jupusdMint": "$JUPUSD_MINT"
    },
    "bitcoin": {
        "network": "$BTC_NETWORK",
        "poolAddress": "$POOL_BTC_ADDR",
        "groupPubkey": "$GROUP_PUBKEY",
        "explorerUrl": "$BTC_EXPLORER"
    },
    "backend": {
        "url": "$BACKEND_URL"
    }
}

with open(networks_path, "w") as f:
    json.dump(networks, f, indent=2)
    f.write("\n")

network = "$NETWORK"
print(f"✓ Updated {networks_path} [{network}]")
PYEOF

# ─── Done ─────────────────────────────────────────────────────────────────────

echo ""
echo "=== Config Sync Complete ==="
echo "Generated from: $STATE_FILE"
echo ""
echo "Files updated:"
echo "  1. $BACKEND_ENV"
echo "  2. $FRONTEND_ENV"
echo "  3. $NETWORKS_JSON"
echo ""
echo "To switch networks:"
echo "  AEGIS_NETWORK=devnet ./scripts/sync-env.sh"
