#!/usr/bin/env bash
#
# sync-env.sh — Single source of truth config generator
#
# Reads {network}-state.json and generates ALL config files:
#   1. backend/.env.{network} + symlink backend/.env
#   2. web/.env.{network} + symlink web/.env.local
#   3. web/src/lib/networks.json (frontend config)
#
# Usage:
#   ./scripts/sync-env.sh
#   UTXOPIA_NETWORK=localnet ./scripts/sync-env.sh
#
# After deploying: update scripts/devnet-state.json, then run this script.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
NETWORK="${UTXOPIA_NETWORK:-devnet}"

echo "=== UTXOpia Config Sync ==="
echo "Network: $NETWORK"
echo ""

# ─── Load state file ──────────────────────────────────────────────────────────

case "$NETWORK" in
  localnet)
    STATE_FILE="$ROOT/scripts/e2e/localnet-state.json"
    ;;
  devnet)
    STATE_FILE="$ROOT/scripts/devnet-state.json"
    ;;
  *)
    echo "ERROR: Unknown network '$NETWORK'. Use: localnet, devnet"
    exit 1
    ;;
esac

if [ ! -f "$STATE_FILE" ]; then
  echo "ERROR: $STATE_FILE not found."
  echo "Run the deploy/init script first."
  exit 1
fi

# Helper to read JSON fields (works without jq)
jval() {
  python3 -c "import json,sys; d=json.load(open('$STATE_FILE')); print(d.get('$1',''))"
}

# ─── Read all values from state file ──────────────────────────────────────────

PROGRAM_ID=$(jval utxopiaProgramId)
BTC_LC_ID=$(jval btcLightClientId)
ZKBTC_MINT=$(jval zkbtcMint)
POOL_STATE=$(jval poolState)
COMMITMENT_TREE=$(jval commitmentTree)
POOL_VAULT=$(jval poolVault)
FROST_VAULT=$(jval frostVault)
POOL_AUTHORITY=$(jval poolAuthority)

WSOL_MINT=$(jval wsolMint)
USDC_MINT=$(jval tUsdcMint)
USDT_MINT=$(jval tUsdtMint)
JUPUSD_MINT=$(jval jupUsdMint)
WSOL_VAULT=$(jval wsolVault)
USDC_VAULT=$(jval tUsdcVault)
USDT_VAULT=$(jval tUsdtVault)
JUPUSD_VAULT=$(jval jupUsdVault)

GROUP_PUBKEY=$(jval btcXOnlyPubKey)
POOL_BTC_ADDR=$(jval poolBtcAddress)
BTC_NETWORK=$(jval btcNetwork)
SOLANA_RPC=$(jval solanaRpc)
BACKEND_URL=$(jval backendUrl)

SIGNING_MODE=$(python3 -c "import json,sys; d=json.load(open('$STATE_FILE')); print(d.get('signingMode','frost'))")

# Ika dWallet integration (nested under "ika" — fall back to empty string if absent).
IKA_PROGRAM_ID=$(python3 -c "import json,sys; d=json.load(open('$STATE_FILE')); print(d.get('ika',{}).get('programId',''))")
IKA_GRPC_ENDPOINT=$(python3 -c "import json,sys; d=json.load(open('$STATE_FILE')); print(d.get('ika',{}).get('grpcEndpoint',''))")
IKA_DWALLET=$(python3 -c "import json,sys; d=json.load(open('$STATE_FILE')); print(d.get('ika',{}).get('dwallet',''))")
IKA_DWALLET_XONLY_PUBKEY=$(python3 -c "import json,sys; d=json.load(open('$STATE_FILE')); print(d.get('ika',{}).get('dwalletXOnlyPubkey',''))")
IKA_CPI_AUTHORITY_BUMP=$(python3 -c "import json,sys; d=json.load(open('$STATE_FILE')); print(d.get('ika',{}).get('cpiAuthorityBump',0))")

# Defaults for fields not in state file
BACKEND_URL="${BACKEND_URL:-http://localhost:3001}"

# Network-specific overrides
case "$NETWORK" in
  localnet)
    SOLANA_RPC="${SOLANA_RPC:-http://localhost:8899}"
    BTC_NETWORK="${BTC_NETWORK:-regtest}"
    BACKEND_URL="${BACKEND_URL:-http://localhost:3001}"
    BTC_EXPLORER="http://localhost:3002/regtest"
    ESPLORA_URL="http://localhost:3002/regtest/api"
    MEMPOOL_WS="false"
    ;;
  devnet)
    SOLANA_RPC="${SOLANA_RPC:-https://api.devnet.solana.com}"
    BTC_NETWORK="${BTC_NETWORK:-testnet4}"
    BTC_EXPLORER="https://mempool.space/testnet4"
    ESPLORA_URL="https://mempool.space/testnet4/api"
    MEMPOOL_WS="true"
    ;;
esac

echo "Program ID:    $PROGRAM_ID"
echo "zkBTC Mint:    $ZKBTC_MINT"
echo "BTC LC:        $BTC_LC_ID"
echo "Group Pubkey:  ${GROUP_PUBKEY:0:16}..."
echo ""

# ─── 1. Generate backend/.env.{network} ──────────────────────────────────────

BACKEND_ENV="$ROOT/backend/.env.$NETWORK"
cat > "$BACKEND_ENV" << EOF
# UTXOpia Backend — $NETWORK (auto-generated by sync-env.sh)
# Source: $STATE_FILE
# Re-generate: UTXOPIA_NETWORK=$NETWORK ./scripts/sync-env.sh

# ─── Solana ──────────────────────────────────────────────────────────────────
UTXOPIA_PROGRAM_ID=$PROGRAM_ID
UTXOPIA_ZKBTC_MINT=$ZKBTC_MINT
UTXOPIA_NETWORK=$NETWORK
UTXOPIA_SOLANA_RPC=$SOLANA_RPC
SOLANA_RPC_URL=$SOLANA_RPC
BTC_LIGHT_CLIENT_PROGRAM_ID=$BTC_LC_ID

# ─── Bitcoin ─────────────────────────────────────────────────────────────────
UTXOPIA_BITCOIN_NETWORK=$BTC_NETWORK
UTXOPIA_BITCOIN_RPC=$ESPLORA_URL
ESPLORA_URL=$ESPLORA_URL
MEMPOOL_API_URL=$ESPLORA_URL
POOL_RECEIVE_ADDRESS=$POOL_BTC_ADDR

# ─── Signing mode (driven by state JSON's "signingMode" field) ──────────────
UTXOPIA_SIGNING_MODE=$SIGNING_MODE

# ─── Ika dWallet (custody for v2 — primary signing path) ────────────────────
UTXOPIA_IKA_PROGRAM_ID=$IKA_PROGRAM_ID
UTXOPIA_IKA_GRPC_ENDPOINT=$IKA_GRPC_ENDPOINT
UTXOPIA_IKA_DWALLET=$IKA_DWALLET
UTXOPIA_IKA_DWALLET_XONLY_PUBKEY=$IKA_DWALLET_XONLY_PUBKEY
UTXOPIA_IKA_CPI_AUTHORITY_BUMP=$IKA_CPI_AUTHORITY_BUMP

# ─── Tracker & Indexer ───────────────────────────────────────────────────────
TRACKER_API_PORT=3001
DEPOSIT_DB_PATH=data/deposits.db
INDEXER_DB_PATH=data/events.db
INDEXER_POLL_INTERVAL_SECS=10
UTXOPIA_DEMO_MODE=1

# ─── Keypairs ────────────────────────────────────────────────────────────────
VERIFIER_KEYPAIR=verifier-keypair.json
RELAYER_KEYPAIR=\${RELAYER_KEYPAIR:?Set RELAYER_KEYPAIR env var}

# ─── WebSocket & Header Relay ────────────────────────────────────────────────
MEMPOOL_WS_ENABLED=$MEMPOOL_WS
MEMPOOL_WS_URL=wss://mempool.space/testnet4/api/v1/ws
HEADER_RELAY_ENABLED=$MEMPOOL_WS
HEADER_BATCH_SIZE=5

# ─── Fees ────────────────────────────────────────────────────────────────────
RELAYER_FEE_SATS=500
UTXOPIA_BROADCAST_MODE=real

# ─── API Auth ────────────────────────────────────────────────────────────────
BACKEND_API_KEY=\${BACKEND_API_KEY:?Set BACKEND_API_KEY env var}

# ─── Allowed Origins ─────────────────────────────────────────────────────────
ALLOWED_ORIGIN=http://localhost:3000

# ─── Logging ─────────────────────────────────────────────────────────────────
RUST_LOG=info,zkbtc=debug
EOF

echo "✓ Generated $BACKEND_ENV"
ln -sf ".env.$NETWORK" "$ROOT/backend/.env"
echo "✓ Symlinked backend/.env → .env.$NETWORK"

# ─── 2. Generate web/.env.{network} ──────────────────────────────────────────

FRONTEND_ENV="$ROOT/web/.env.$NETWORK"
cat > "$FRONTEND_ENV" << EOF
# UTXOpia Frontend — $NETWORK (auto-generated by sync-env.sh)
# Source: $STATE_FILE
# Re-generate: UTXOPIA_NETWORK=$NETWORK ./scripts/sync-env.sh

NEXT_PUBLIC_NETWORK=$NETWORK
NEXT_PUBLIC_SOLANA_RPC_URL=$SOLANA_RPC
NEXT_PUBLIC_BTC_NETWORK=$BTC_NETWORK
NEXT_PUBLIC_UTXOPIA_PROGRAM_ID=$PROGRAM_ID
NEXT_PUBLIC_ZKBTC_MINT=$ZKBTC_MINT
EOF

[ -n "$USDC_MINT" ] && echo "NEXT_PUBLIC_USDC_MINT=$USDC_MINT" >> "$FRONTEND_ENV"
[ -n "$USDT_MINT" ] && echo "NEXT_PUBLIC_USDT_MINT=$USDT_MINT" >> "$FRONTEND_ENV"
[ -n "$WSOL_MINT" ] && echo "NEXT_PUBLIC_WSOL_MINT=$WSOL_MINT" >> "$FRONTEND_ENV"
[ -n "$JUPUSD_MINT" ] && echo "NEXT_PUBLIC_JUPUSD_MINT=$JUPUSD_MINT" >> "$FRONTEND_ENV"

cat >> "$FRONTEND_ENV" << EOF

# Backend API
BACKEND_API_URL=$BACKEND_URL
NEXT_PUBLIC_BACKEND_API_URL=$BACKEND_URL
BACKEND_API_KEY=$([ "$NETWORK" = "devnet" ] && printf '%s' "utxopia-backend-2026" || printf '%s' "localnet-dev-key")
EOF

echo "✓ Generated $FRONTEND_ENV"
ln -sf ".env.$NETWORK" "$ROOT/web/.env.local"
echo "✓ Symlinked web/.env.local → .env.$NETWORK"

# ─── 3. Generate web/src/lib/networks.json ───────────────────────────────────
#
# This is the frontend's runtime config. We update ONLY the current network's
# section, preserving other networks' config.

NETWORKS_JSON="$ROOT/web/src/lib/networks.json"

# Build the network block with python3 (no jq needed)
python3 << PYEOF
import json, os

networks_path = "$NETWORKS_JSON"

# Load existing networks.json
if os.path.exists(networks_path):
    with open(networks_path) as f:
        networks = json.load(f)
else:
    networks = {}

# Update the current network section
networks["$NETWORK"] = {
    "solana": {
        "rpcUrl": "$SOLANA_RPC",
        "utxopiaProgramId": "$PROGRAM_ID",
        "btcLightClientId": "$BTC_LC_ID",
        "chadbufferId": "C5RpjtTMFXKVZCtXSzKXD4CDNTaWBg3dVeMfYvjZYHDF"
    },
    "tokens": {
        "zkbtcMint": "$ZKBTC_MINT",
        "usdcMint": "$USDC_MINT",
        "usdtMint": "$USDT_MINT",
        "wsolMint": "$WSOL_MINT",
        "jupusdMint": "$JUPUSD_MINT"
    },
    "bitcoin": {
        "network": "$BTC_NETWORK",
        "poolAddress": "$POOL_BTC_ADDR",
        "groupPubkey": "$GROUP_PUBKEY",
        "explorerUrl": "$BTC_EXPLORER"
    },
    "ika": {
        "programId": "$IKA_PROGRAM_ID",
        "grpcEndpoint": "$IKA_GRPC_ENDPOINT",
        "dwallet": "$IKA_DWALLET",
        "dwalletXOnlyPubkey": "$IKA_DWALLET_XONLY_PUBKEY"
    },
    "backend": {
        "url": "$BACKEND_URL"
    }
}

with open(networks_path, "w") as f:
    json.dump(networks, f, indent=2)
    f.write("\n")

network = "$NETWORK"
print(f"✓ Updated {networks_path} [{network}]")
PYEOF

# ─── Done ─────────────────────────────────────────────────────────────────────

echo ""
echo "=== Config Sync Complete ==="
echo "Generated from: $STATE_FILE"
echo ""
echo "Files updated:"
echo "  1. $BACKEND_ENV"
echo "  2. $FRONTEND_ENV"
echo "  3. $NETWORKS_JSON"
echo ""
echo "To switch networks:"
echo "  UTXOPIA_NETWORK=devnet ./scripts/sync-env.sh"
