#!/usr/bin/env bash
#
# sync-env.sh — Generate .env files for all services from localnet-state.json
#
# Usage:
#   ./scripts/sync-env.sh              # defaults to AEGIS_NETWORK=localnet
#   AEGIS_NETWORK=devnet ./scripts/sync-env.sh
#
# For localnet: reads scripts/e2e/localnet-state.json as source of truth
# For devnet:   uses hardcoded devnet program IDs
#
# Generated files:
#   backend/.env.{network}       + symlink backend/.env → backend/.env.{network}
#   aegis-app/.env.{network}     + symlink aegis-app/.env.local → aegis-app/.env.{network}

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
NETWORK="${AEGIS_NETWORK:-localnet}"

echo "=== Aegis Env Sync ==="
echo "Network: $NETWORK"
echo "Root:    $ROOT"
echo ""

# ─── Network-specific values ─────────────────────────────────────────────────

case "$NETWORK" in
  localnet)
    STATE_FILE="$ROOT/scripts/e2e/localnet-state.json"
    if [ ! -f "$STATE_FILE" ]; then
      echo "ERROR: $STATE_FILE not found."
      echo "Run the init script first: cd scripts/e2e && bun run init"
      exit 1
    fi

    # Read values from localnet-state.json
    PROGRAM_ID=$(python3 -c "import json; print(json.load(open('$STATE_FILE'))['aegisProgramId'])")
    ZKBTC_MINT=$(python3 -c "import json; print(json.load(open('$STATE_FILE'))['zkbtcMint'])")
    BTC_LC_ID=$(python3 -c "import json; print(json.load(open('$STATE_FILE'))['btcLightClientId'])")
    USDC_MINT=$(python3 -c "import json; print(json.load(open('$STATE_FILE')).get('tUsdcMint', ''))")
    WSOL_MINT=$(python3 -c "import json; print(json.load(open('$STATE_FILE')).get('tWsolMint', ''))")
    POOL_ADDR=$(python3 -c "import json; print(json.load(open('$STATE_FILE')).get('poolBtcAddress', ''))")

    SOLANA_RPC="http://localhost:8899"
    BTC_NETWORK="regtest"
    BTC_RPC="http://localhost:3002/regtest/api"
    ESPLORA_URL="http://localhost:3002/regtest/api"
    BACKEND_URL="http://localhost:3001"
    MEMPOOL_WS="false"
    ;;

  devnet)
    # Read from devnet-state.json if available (generated by deploy-devnet.sh)
    DEVNET_STATE="$ROOT/scripts/devnet-state.json"
    if [ -f "$DEVNET_STATE" ] && command -v jq &>/dev/null; then
      PROGRAM_ID=$(jq -r '.aegisProgramId // empty' "$DEVNET_STATE")
      ZKBTC_MINT=$(jq -r '.zkbtcMint // empty' "$DEVNET_STATE")
      BTC_LC_ID=$(jq -r '.btcLightClientId // empty' "$DEVNET_STATE")
      USDC_MINT=$(jq -r '.tUsdcMint // empty' "$DEVNET_STATE")
      WSOL_MINT=""
      POOL_ADDR=$(jq -r '.poolBtcAddress // empty' "$DEVNET_STATE")
    else
      # Fallback hardcoded values
      PROGRAM_ID="7JJeVjVCy1fZqCDWvf41R7LuTWirTjX7Tp6suC2WVUMQ"
      ZKBTC_MINT="G5CHaLkWjdUxxmnrVqNLQ29K7PoNwJAzvVT11jjkdGKC"
      BTC_LC_ID="Ho6UTeF8yFnRdCK15tSZtcJozvkDABJZWYxkgGyWAfyq"
      USDC_MINT=""
      WSOL_MINT=""
      POOL_ADDR="tb1pksj664hdqkzvw2tlfvqshnevxt2qdutk47p9z964dkcsxazmf0vsjas4n4"
    fi

    SOLANA_RPC="https://api.devnet.solana.com"
    BTC_NETWORK="testnet4"
    BTC_RPC="https://mempool.space/testnet4/api"
    ESPLORA_URL="https://mempool.space/testnet4/api"
    BACKEND_URL="https://api-aegis.amidoggy.xyz"
    MEMPOOL_WS="true"
    ;;

  *)
    echo "ERROR: Unknown network '$NETWORK'. Use: localnet, devnet"
    exit 1
    ;;
esac

echo "Program ID:  $PROGRAM_ID"
echo "zkBTC Mint:  $ZKBTC_MINT"
echo "BTC LC:      $BTC_LC_ID"
[ -n "$USDC_MINT" ] && echo "USDC Mint:   $USDC_MINT"
[ -n "$WSOL_MINT" ] && echo "wSOL Mint:   $WSOL_MINT"
echo ""

# ─── Generate backend/.env.{network} ─────────────────────────────────────────

BACKEND_ENV="$ROOT/backend/.env.$NETWORK"
cat > "$BACKEND_ENV" << EOF
# Aegis Backend — $NETWORK (auto-generated by sync-env.sh)
# Re-generate: AEGIS_NETWORK=$NETWORK ./scripts/sync-env.sh

# ─── Solana ──────────────────────────────────────────────────────────────────
AEGIS_PROGRAM_ID=$PROGRAM_ID
AEGIS_ZKBTC_MINT=$ZKBTC_MINT
AEGIS_NETWORK=$NETWORK
AEGIS_SOLANA_RPC=$SOLANA_RPC
SOLANA_RPC_URL=$SOLANA_RPC
BTC_LIGHT_CLIENT_PROGRAM_ID=$BTC_LC_ID

# ─── Bitcoin ─────────────────────────────────────────────────────────────────
AEGIS_BITCOIN_NETWORK=$BTC_NETWORK
AEGIS_BITCOIN_RPC=$BTC_RPC
ESPLORA_URL=${ESPLORA_URL:-$BTC_RPC}
MEMPOOL_API_URL=$BTC_RPC
POOL_RECEIVE_ADDRESS=$POOL_ADDR

# ─── FROST Signing ───────────────────────────────────────────────────────────
AEGIS_SIGNING_MODE=frost
AEGIS_FROST_THRESHOLD=2
AEGIS_FROST_PARTICIPANTS=3
AEGIS_FROST_SIGNER_URLS=http://localhost:9001,http://localhost:9002,http://localhost:9003
AEGIS_FROST_KEY_SHARE=placeholder
AEGIS_FROST_GROUP_PUBKEY=b425ad56ed0584c7297f4b010bcf2c32d406f176af825117556db103745b4bd9
AEGIS_FROST_API_KEY=29372dc836a25d7bdcdbd2fa63fbfcc0d00f06ca710a3aa935b61cf5d6426912

# ─── Tracker & Indexer ───────────────────────────────────────────────────────
TRACKER_API_PORT=3001
DEPOSIT_DB_PATH=data/deposits.db
INDEXER_DB_PATH=data/events.db
INDEXER_POLL_INTERVAL_SECS=10
AEGIS_DEMO_MODE=1

# ─── Keypairs ────────────────────────────────────────────────────────────────
VERIFIER_KEYPAIR=verifier-keypair.json
RELAYER_KEYPAIR=[50,128,114,217,238,93,48,208,84,69,168,140,72,35,173,128,57,239,14,139,145,69,241,221,89,52,36,156,104,238,166,101,13,98,59,211,107,90,137,69,248,31,168,162,72,104,198,209,65,164,43,83,227,202,213,91,45,163,238,203,91,107,68,170]

# ─── WebSocket & Header Relay ────────────────────────────────────────────────
MEMPOOL_WS_ENABLED=$MEMPOOL_WS
MEMPOOL_WS_URL=wss://mempool.space/testnet4/api/v1/ws
HEADER_RELAY_ENABLED=$MEMPOOL_WS
HEADER_BATCH_SIZE=5

# ─── Fees ──────────────────────────────────────────────────────────────────
RELAYER_FEE_SATS=500
AEGIS_BROADCAST_MODE=real

# ─── API Auth ───────────────────────────────────────────────────────────────
BACKEND_API_KEY=aegis-backend-2026

# ─── Allowed Origins ────────────────────────────────────────────────────────
ALLOWED_ORIGIN=http://localhost:3000

# ─── Logging ─────────────────────────────────────────────────────────────────
RUST_LOG=info,zkbtc=debug
EOF

echo "✓ Generated $BACKEND_ENV"

# Symlink backend/.env → backend/.env.{network}
ln -sf ".env.$NETWORK" "$ROOT/backend/.env"
echo "✓ Symlinked backend/.env → .env.$NETWORK"

# ─── Generate aegis-app/.env.{network} ───────────────────────────────────────

FRONTEND_ENV="$ROOT/aegis-app/.env.$NETWORK"
cat > "$FRONTEND_ENV" << EOF
# Aegis Frontend — $NETWORK (auto-generated by sync-env.sh)
# Re-generate: AEGIS_NETWORK=$NETWORK ./scripts/sync-env.sh

NEXT_PUBLIC_NETWORK=$NETWORK
NEXT_PUBLIC_SOLANA_RPC_URL=$SOLANA_RPC
NEXT_PUBLIC_BTC_NETWORK=$BTC_NETWORK
NEXT_PUBLIC_AEGIS_PROGRAM_ID=$PROGRAM_ID
NEXT_PUBLIC_ZKBTC_MINT=$ZKBTC_MINT
EOF

# Add optional mints
[ -n "$USDC_MINT" ] && echo "NEXT_PUBLIC_USDC_MINT=$USDC_MINT" >> "$FRONTEND_ENV"
[ -n "$WSOL_MINT" ] && echo "NEXT_PUBLIC_WSOL_MINT=$WSOL_MINT" >> "$FRONTEND_ENV"

cat >> "$FRONTEND_ENV" << EOF

# Backend API
BACKEND_API_URL=$BACKEND_URL
NEXT_PUBLIC_BACKEND_API_URL=$BACKEND_URL
BACKEND_API_KEY=localnet-dev-key
EOF

echo "✓ Generated $FRONTEND_ENV"

# Symlink aegis-app/.env.local → .env.{network}
ln -sf ".env.$NETWORK" "$ROOT/aegis-app/.env.local"
echo "✓ Symlinked aegis-app/.env.local → .env.$NETWORK"

echo ""
echo "=== Done ==="
echo "All .env files synced to $NETWORK."
echo ""
echo "To switch networks:"
echo "  AEGIS_NETWORK=devnet ./scripts/sync-env.sh"
